module.exports = {
	// Load credentials from environment variables; do not hardcode secrets.
	apps: [
		{
			name: "nest-backend",
			script: "dist/src/main.js",
			instances: 1,
			autorestart: true,
			watch: false,
			max_memory_restart: "1G",
			env: {
				NODE_ENV: "development",
				PORT: process.env.PORT || 4000,
				MONGODB_CONNECTION_URL: process.env.MONGODB_CONNECTION_URL,
				AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME,
				AWS_REGION: process.env.AWS_REGION || "us-east-1",
				AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
				AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
				MONGO_URI: process.env.MONGO_URI,
				SEED_PASSWORD: process.env.SEED_PASSWORD,
				JWT_SECRET: process.env.JWT_SECRET,
				JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || "24h",
				SMTP_HOST: process.env.SMTP_HOST,
				SMTP_PORT: process.env.SMTP_PORT || 587,
				SMTP_USER: process.env.SMTP_USER,
				SMTP_PASSWORD: process.env.SMTP_PASSWORD,
				SMTP_FROM: process.env.SMTP_FROM,
			},
			env_production: {
				NODE_ENV: "production",
				PORT: process.env.PORT || 4000,
				MONGODB_CONNECTION_URL: process.env.MONGODB_CONNECTION_URL,
				AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME,
				AWS_REGION: process.env.AWS_REGION || "us-east-1",
				AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
				AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
				MONGO_URI: process.env.MONGO_URI,
				SEED_PASSWORD: process.env.SEED_PASSWORD,
				JWT_SECRET: process.env.JWT_SECRET,
				JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || "24h",
				SMTP_HOST: process.env.SMTP_HOST,
				SMTP_PORT: process.env.SMTP_PORT || 587,
				SMTP_USER: process.env.SMTP_USER,
				SMTP_PASSWORD: process.env.SMTP_PASSWORD,
				SMTP_FROM: process.env.SMTP_FROM,
			},
		},
	],
};
